# Generated by Django 4.2.4 on 2023-09-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('desc_short', models.CharField(max_length=5000, null=True)),
                ('desc_detailed', models.CharField(max_length=5000, null=True)),
                ('horarios', models.CharField(max_length=350, null=True)),
                ('inicio', models.DateTimeField(null=True)),
                ('cierre', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('localidad', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('dni', models.PositiveIntegerField(null=True)),
                ('localidad', models.CharField(max_length=255, null=True)),
                ('nacimiento', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('escuela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clan.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadEvaluativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('descripcion', models.CharField(max_length=5000, null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clan.alumno')),
            ],
        ),
    ]
