# Generated by Django 4.2.4 on 2023-09-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clan.escuela'),
        ),
    ]
