# Generated by Django 4.2.4 on 2023-10-21 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clan', '0004_alumno_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.BooleanField(null=True)),
                ('question_2', models.BooleanField(null=True)),
                ('question_3', models.BooleanField(null=True)),
                ('question_4', models.BooleanField(null=True)),
                ('question_5', models.IntegerField(null=True)),
                ('question_6', models.IntegerField(null=True)),
                ('question_7', models.IntegerField(null=True)),
                ('question_8', models.IntegerField(null=True)),
                ('question_9', models.IntegerField(null=True)),
                ('question_10', models.IntegerField(null=True)),
                ('question_11', models.FileField(null=True, upload_to='')),
                ('question_12_s1', models.BooleanField(null=True)),
                ('question_12_s2', models.BooleanField(null=True)),
                ('question_12_s3', models.BooleanField(null=True)),
                ('question_12_s4', models.BooleanField(null=True)),
                ('question_12_s5', models.BooleanField(null=True)),
                ('question_12_s6', models.BooleanField(null=True)),
                ('question_12_s7', models.BooleanField(null=True)),
                ('question_13_s1', models.BooleanField(null=True)),
                ('question_13_s2', models.BooleanField(null=True)),
                ('question_13_s3', models.BooleanField(null=True)),
                ('question_13_s4', models.BooleanField(null=True)),
                ('question_13_s5', models.BooleanField(null=True)),
                ('question_13_s6', models.BooleanField(null=True)),
                ('question_14', models.IntegerField(null=True)),
                ('question_15', models.IntegerField(null=True)),
                ('question_15_extra', models.TextField(blank=True, max_length=5000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
