# Generated by Django 4.2.4 on 2023-09-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_curso_slug_alter_estudiante_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
