# Generated by Django 4.2.4 on 2023-10-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_alter_estudiante_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='cue',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
