# Generated by Django 4.2.4 on 2023-10-06 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_institucion_cue'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
