# Generated by Django 4.2.4 on 2023-10-21 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_estudiante_created_estudiante_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='curso',
            name='familia_profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='aplicacion.familiaprofesional'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='aplicacion.institucion'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='aplicacion.curso'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='partido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituciones', to='aplicacion.partido'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='aplicacion.provincia'),
        ),
    ]
