# Generated by Django 4.2.4 on 2023-10-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_alter_estudiante_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='aplicacion.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='familia_profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.familiaprofesional'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.institucion'),
        ),
    ]
