# Generated by Django 4.2.4 on 2023-10-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_remove_estudiante_curso_estudiante_cursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, to='aplicacion.estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='aplicacion.curso'),
        ),
    ]
