# Generated by Django 4.2.4 on 2023-10-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_avatarpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarpdf',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/avataresPDF'),
        ),
    ]
