# Generated by Django 4.2.4 on 2023-10-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0020_avatarpdf_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, null=True)),
                ('dni', models.IntegerField(max_length=8, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mensaje', models.TextField(max_length=512, null=True)),
                ('atendido', models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
