# Generated by Django 4.2.4 on 2023-10-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0021_queja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='atendido',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='queja',
            name='dni',
            field=models.IntegerField(null=True),
        ),
    ]
